name: Update Architecture Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'CHANGELOG.md'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper analysis
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update architecture diagrams
      run: node docs/architecture/update-diagrams.js
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code docs/architecture || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Commit changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/architecture
        git commit -m "docs: update architecture documentation [skip ci]"
    
    - name: Push changes
      if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
    # For pull requests, we'll commit the changes directly to the PR branch
    # instead of creating a new PR to avoid circular references
    - name: Commit changes to PR branch
      if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/architecture
        git commit -m "docs: update architecture documentation [skip ci]"
        git push origin HEAD:${{ github.head_ref }}
