name: Update Architecture Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'CHANGELOG.md'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper analysis
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update architecture diagrams
      run: node docs/architecture/update-diagrams.js
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code docs/architecture || echo "::set-output name=changes::true"
    
    - name: Commit changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/architecture
        git commit -m "docs: update architecture documentation [skip ci]"
    
    - name: Push changes
      if: steps.git-check.outputs.changes == 'true' && github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
    - name: Create PR for documentation update
      if: steps.git-check.outputs.changes == 'true' && github.event_name == 'pull_request'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "docs: update architecture documentation"
        title: "docs: update architecture documentation"
        body: |
          This PR updates the architecture documentation to reflect changes in the codebase.
          
          The diagrams have been automatically generated based on the current state of the codebase.
        branch: docs/update-architecture-${{ github.event.pull_request.number }}
        base: ${{ github.head_ref }}
